# @api = http://localhost:4000
@api = http://127.0.0.1:3000

GET {{api}}/videos

###

GET {{api}}/videos/65240c9c654142977c07c7f9

###

POST {{api}}/videos
Content-Type: application/json
# PARA QUE FUNCIONE, DEBE HABER UNA LINEA VACIA ENTRE LA DECLARACION Content-Type, Y EL JSON

{
    "url": "https://www.youtube.com/watch?v=_RZ-T6TxP7w",
    "title": "MERN STACK & Typescript (Mongodb, Express, React, Node con Typescript) - #1 Backend",
    "description": "Un video de MERN stack"
}

###

DELETE {{api}}/videos/6526b88e490323981928b16c

###

PUT {{api}}/videos/6526a9fdcadad47254adc413
Content-Type: application/json
# PARA QUE FUNCIONE, DEBE HABER UNA LINEA VACIA ENTRE LA DECLARACION Content-Type, Y EL JSON

{
    "title": "nuevo titulo, MERN STACK"
}
